from .latent_aspect_ratio import NODE_CLASS_MAPPINGS as LATENT_CLASS_MAPPINGS
from .latent_aspect_ratio import NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY_NAME_MAPPINGS

from .pixel_art_downscale import NODE_CLASS_MAPPINGS as PIXEL_CLASS_MAPPINGS
from .pixel_art_downscale import NODE_DISPLAY_NAME_MAPPINGS as PIXEL_DISPLAY_NAME_MAPPINGS

from .prompt_studio import NODE_CLASS_MAPPINGS as STUDIO_CLASS_MAPPINGS
from .prompt_studio import NODE_DISPLAY_NAME_MAPPINGS as STUDIO_DISPLAY_NAME_MAPPINGS

from .image_effects import NODE_CLASS_MAPPINGS as EFFECTS_CLASS_MAPPINGS
from .image_effects import NODE_DISPLAY_NAME_MAPPINGS as EFFECTS_DISPLAY_NAME_MAPPINGS

from .hires_ksampler import NODE_CLASS_MAPPINGS as HIRES_CLASS_MAPPINGS
from .hires_ksampler import NODE_DISPLAY_NAME_MAPPINGS as HIRES_DISPLAY_NAME_MAPPINGS

from .flux_klein_nodes import NODE_CLASS_MAPPINGS as KLEIN_CLASS_MAPPINGS
from .flux_klein_nodes import NODE_DISPLAY_NAME_MAPPINGS as KLEIN_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {
    **LATENT_CLASS_MAPPINGS,
    **PIXEL_CLASS_MAPPINGS,
    **STUDIO_CLASS_MAPPINGS,
    **EFFECTS_CLASS_MAPPINGS,
    **HIRES_CLASS_MAPPINGS,
    **KLEIN_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LATENT_DISPLAY_NAME_MAPPINGS,
    **PIXEL_DISPLAY_NAME_MAPPINGS,
    **STUDIO_DISPLAY_NAME_MAPPINGS,
    **EFFECTS_DISPLAY_NAME_MAPPINGS,
    **HIRES_DISPLAY_NAME_MAPPINGS,
    **KLEIN_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

